### ISSUE TITLE
Micro Square root Calc is not in a folder and causes the game not to be added to code.thumby.us

### ISSUE THREAD

**Issue by BBfiChe1** [TinyCircuits/TinyCircuits-Thumby-Games#191]
Hi there I noticed that a recently added game called "Micro Square Root Calc" was not merged correctly into the main tiny circuits repository. To fix this you can add a folder called "Micro Square Root Calc" and delete the old files and it will all be fixed.

**Comment by BBfiChe1** [comment]
[Micro Square Root Calc.zip](https://github.com/TinyCircuits/TinyCircuits-Thumby-Games/files/12651782/Micro.Square.Root.Calc.zip)
Unzip the file attached and add it to the main repository in order to fix it and add the game to the arcade. Let me know if there are any further issues.

**Comment by BBfiChe1** [comment]
Also The files that need to be moved to a folder are:
- Micro Square root Calc.py
- thumby_emluator_screenshot.png
- arcade_description.txt
- arcade_title_video.webm
Please Move all 4 files stated above to the corrected folder to fix the issue. Thanks!

**Comment by TinyCircuits** [comment]
Fixed https://github.com/TinyCircuits/TinyCircuits-Thumby-Games/commit/73d3b6e148ee9194fb947e79540221d9ccd343df
