### ISSUE TITLE
Tiny Rogue only loading to title screen?

### ISSUE THREAD

**Issue by BlakeBild** [TinyCircuits/TinyCircuits-Thumby-Games#47]
I can't seem to get passed the title screen. 
It just seems like it's frozen, but I did confirm that it is looping through the title screen, inputs just aren't doing anything.   ¯\\_ (ツ)_/¯

**Comment by AyreGuitar** [comment]
Are you running it in the Emulator? FWIW I can never get past the title screen in the emulator, but is fine when run on a real Thumby.

**Comment by BlakeBild** [comment]
didn't realize this was still open, my bad! Work fine directly on thumby as said by AyreGuitar
