### ISSUE TITLE
Requested screenshot for TinyMonsters

### ISSUE THREAD

**Issue by JohnnyRtx** [TinyCircuits/TinyCircuits-Thumby-Games#8]
Here:
Also, when do you plan to ship the light gray thumbys? 
![Screenshot 2022-01-11 6 17 28 PM](https://user-images.githubusercontent.com/97552431/149036519-57c55dcf-7aae-4e51-9cd2-ef4fb419eb01.png)

**Comment by JohnnyRtx** [comment]
It works now, I closed the main game file and just kept the readme file open, when I was supposed to run off the main game. Sorry :/

**Comment by jmtinycircuits** [comment]
Glad you got it working.

We have started shipping out light gray Thumbys.
