### ISSUE TITLE
Tiny_Monster_Hunter does not start on Thumby

### ISSUE THREAD

**Issue by FlorianFrankeWN** [TinyCircuits/TinyCircuits-Thumby-Games#9]
As the title says: the game does not start on the thumby and freezes. This is what is printed to the console when tested with thumby plugged in and in debug mode:
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
MemoryError: memory allocation failed, allocating 3154 bytes
```

**Comment by jmtinycircuits** [comment]
Yeah, same here. The game was tested by running it directly through the console which didn't load the main menu. The main menu takes up a bit of ram and there is no way to free it all once the game imports.

Although a great game, it will need to be removed for now.

To improve the likelihood if it running, the actual code size needs to be reduced. Code used often should be placed into functions and modularized, and sprites should be made into binary sprite files (use the import sprite button in the IDE).

@BlakeBild

**Comment by BlakeBild** [comment]
Good morning,

I’m trying to work on this a little bit, do you know about how much memory
the main menu takes up so I can work it down?

Thanks for your time,
Blake
